# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MedX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MedX
  pod 'SendBirdSDK'
  pod 'Alamofire', '< 5.0'
end
